### ISSUE TITLE
Steamunlocked unsafe

### ISSUE THREAD

**Issue by TheRealArchie** [IdleEndeavor/gamesearch#1]
Steamunlocked is unsafe, stop displaying it in searches please. 
It was recently discovered that steamunlocked are straight up ripping games from dodgy sites like IGG etc. Chances of infecting your PC are high if you continue using it

**Comment by IdleEndeavor** [comment]
Thank you for bringing this to my notice/ 
I have removed Steamunlocked from my list of sources.
