### ISSUE TITLE
Separate mobile search

### ISSUE THREAD

**Issue by maplepy** [IdleEndeavor/gamesearch#2]
Hey! It's me again, don't know if you remember me aha

I was wondering if you had any plan to separate iOS and Android search results for the mobile filter

I tried searching a game for iOS and was bombarded with .apk where I was looking for .ipa

**Comment by IdleEndeavor** [comment]
Hey hey

I do in fact have plans to separate them both. I too had noticed that the results were too bloated when they were only under one tab. I'll be making this update soon.

Stay tuned! and thanks for letting me know of your concern.

**Comment by IdleEndeavor** [comment]
The update has been made. 
You should now see different filters for Android and iOS alongside a third one that generally searches for mobile apps. 
I'll consider retiring the 'Mobile' filter at a later time.
Thank you for bringing this issue up.

**Comment by maplepy** [comment]
Thanks for your hardwork :)

No problem, I don't think it's very bothering anyone and could maybe help some people, not sure
