### ISSUE TITLE
(Feature) Add multiple engines

### ISSUE THREAD

**Issue by OshekharO** [IdleEndeavor/gamesearch#4]
Hii can you implement multiple cse api? Like here: https://github.com/yrq110/TinyGoogle/blob/master/data/engine.json

**Comment by IdleEndeavor** [comment]
It would be very helpful if you could explain what benefits this brings.

**Comment by OshekharO** [comment]
@IdleEndeavor 

Benefits:

Incase search limit is reached no need to change api again and again ( it's beneficial if daily page view ia high )

**Comment by IdleEndeavor** [comment]
I can certainly see why this would be useful. However, we experience no such limitations at the moment. If it does come up at a later date, I'll surely use this.

Thank you.
